services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/cert"
      - "./config:/etc/nginx/conf.d"
    extra_hosts:
      - "host.docker.internal:host-gateway"
